### ISSUE TITLE
Doesn't work with Vue3

### ISSUE THREAD

**Issue by qirh** [g33kio/vue-mousetrap#4]
error when using Vue3 `Uncaught TypeError: Cannot set property '$mousetrap' of undefined`

**Comment by g33kio** [comment]
fixed in 1.0.3

**Comment by frank-amsterdam** [comment]
version 1.0.3 seems to break Vue 2 compatability, now giving the same error @qirh had in Vue 3

**Comment by g33kio** [comment]
Please see the updated readme file, vue 2 now needs to be imported as so:

import Vue from 'vue'
import VueMousetrapPlugin from 'vue-mousetrap/vue2'
Vue.use(VueMousetrapPlugin)
