### ISSUE TITLE
How to use with composition API?

### ISSUE THREAD

**Issue by crystalfp** [g33kio/vue-mousetrap#6]
I try to use this plugin with a vue 3 application written in typescript. After loading the plugin in `main.ts` this way (removed various imports):
```
import VueMousetrapPlugin from "vue-mousetrap"
createApp(App).use(store, key).use(VueMousetrapPlugin).mount("#app")
```
But how to call it from a component that use the new composition API with `<script setup lang="ts">`?
Here `$mousetrap`, `this.$mousetrap` and other variations are not defined. For a Vuex store, that has a similar interface (`this.$store`) with the new composition API there is a call that returns a `store` that replaces `this.$store`. Any suggestion? Thanks!

**Comment by oskarr** [comment]
I've had the same (or at least a very similar) problem, and I managed to solve it by replacing this package with a typed version of [index.js](https://github.com/g33kio/vue-mousetrap/blob/master/index.js), combined with the instructions on type-declaring `globalProperties` found in the [Vue3 docs](https://v3.vuejs.org/guide/typescript-support.html#augmenting-types-for-globalproperties):

```typescript
import { createApp, App as AppType } from 'vue';
import mousetrap, { MousetrapStatic } from 'mousetrap';
import App from './App.vue';

// Based on https://github.com/g33kio/vue-mousetrap/blob/master/index.js
const VueMousetrapPlugin = {
  install(app: AppType): void {
    app.config.globalProperties.$mousetrap = mousetrap;
  },
};

// See https://v3.vuejs.org/guide/typescript-support.html#augmenting-types-for-globalproperties
declare module '@vue/runtime-core' {
  export interface ComponentCustomProperties {
    $mousetrap: MousetrapStatic
  }
}

createApp(App).use(VueMousetrapPlugin).mount('#app');
```
Perhaps I'll play around with adding something like the above to the package directly when I have time. I'm not very familiar with making npm packages, so perhaps someone more experienced could do it more quickly.

Edit: I saw that there were some instructions [here](https://github.com/ahoiroman/vue-mousetrap/tree/patch-1) on using it with `inject`.

**Comment by crystalfp** [comment]
Thanks for the suggestion! At the moment I call it like a regular library and it works, but your method is much more elegant. Also I'll try the inject way. Thanks!
