### ISSUE TITLE
Usage with NuxtJS (3)

### ISSUE THREAD

**Issue by ahoiroman** [g33kio/vue-mousetrap#8]
Hello there,

thank you for your plugin and the work related to it.

May I ask: Are there any possibilities to use this in NuxtJS 3?

I created a plugin like this:

```js
import VueMousetrapPlugin from 'vue-mousetrap'

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(VueMousetrapPlugin);
    return {
        provide: {
            mousetrap: () => nuxtApp.vueApp.config.globalProperties.$mousetrap
        }
    }
});
```

But if I try to use it in a component like this:

```vue
$mousetrap(['command+k', 'ctrl+k'], () => {
            console.log("Test")
            nextTick(() => comboboxinput.value.$el.focus())
        });
```

I don't get an error, but the `Test` is not printed out, if I hit ctrl+k.

**Comment by g33kio** [comment]
The mousetrap library is meant to be client side, and checks for the existence of window in order to load. Since Nuxt is server side and does not have a "window" this plugin would not work for Nuxt applications.
